PATH=["/usr/share/arduino-1.0/hardware/tools/avr/bin", '/bin', '/usr/bin']
env = Environment(tools=["default", "arduino"], ENV={"PATH":PATH})
env.ConfigureBoard("mega2560")

env.Replace(UPLOAD_PORT="/dev/ttyACM0")
env.Append(CCFLAGS = "-DSERIAL_CONN".split())
env.Append(CCFLAGS = "-DNUM_ACTIONS=20".split())
env.Append(CCFLAGS = "-DNUM_EVENTS=25".split())

core = env.ArduinoCore()
shet_lib = env.ArduinoLibrary("shetsource", "../SHETSource/arduino/lib")
sketch = env.Sketch("arduino", ["arduino.cpp", shet_lib, core])

env.Upload(sketch)
